### ISSUE TITLE
Family Guy: Star Wars series

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#17]
[Blue Harvest (2007)](http://www.imdb.com/title/tt0888817)
[Something, Something, Something Dark Side (2010)](http://www.imdb.com/title/tt1329665)
[It's a Trap (2010)](http://www.imdb.com/title/tt1701991)

**Comment by buhman** [comment]
Failed to find tt1329665 at reasonable quality.

**Comment by buhman** [comment]
tt0888817 and tt1701991 queued.

**Comment by buhman** [comment]
> 15:23:58 +halosghost really, Blue Harvest alone is good enough for me, the other ones sucked
