### ISSUE TITLE
Marvel Cinematic Universe

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#24]
Phase One
------------

[Iron Man (2008)](http://www.imdb.com/title/tt0371746)
[The Incredible Hulk (2008)](http://www.imdb.com/title/tt0800080)
[Iron Man 2 (2010)](http://www.imdb.com/title/tt1228705)
[Thor (2011)](http://www.imdb.com/title/tt0800369)
[Captain America: The First Avenger (2011)](http://www.imdb.com/title/tt0458339)
[The Avengers (2012)](http://www.imdb.com/title/tt0848228)

Phase Two
------------

[Iron Man 3 (2013)](http://www.imdb.com/title/tt1300854)
[Thor: Dark World (2013)](http://www.imdb.com/title/tt1981115)

**Comment by buhman** [comment]
remaining:

* thor*
* hulk
* captain
* avengers

**Comment by buhman** [comment]
queued.
