### ISSUE TITLE
Pirates of the Caribbean

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#30]
* [Pirates of the Caribbean: The Curse of the Black Pearl (2003)](http://www.imdb.com/title/tt0325980)
* [Pirates of the Caribbean: Dead Man's Chest (2006)](http://www.imdb.com/title/tt0383574)
* [Pirates of the Caribbean: At World's End (2007)](http://www.imdb.com/title/tt0449088)
* [Pirates of the Caribbean: On Stranger Tides (2011)](http://www.imdb.com/title/tt1298650)

**Comment by buhman** [comment]
Queued.
