### ISSUE TITLE
007

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#31]
[Dr. No (1962)](http://www.imdb.com/title/tt0055928)
[From Russia with Love (1963)](http://www.imdb.com/title/tt0057076)
[Goldfinger (1964)](http://www.imdb.com/title/tt0058150)
[Thunderball (1965)](http://www.imdb.com/title/tt0059800)
[You Only Live Twice (1967)](http://www.imdb.com/title/tt0062512)
[On Her Majesty's Secret Service (1969)](http://www.imdb.com/title/tt0064757)
[Diamonds are Forever (1971)](http://www.imdb.com/title/tt0066995)
[Live and Let Die (1973)](http://www.imdb.com/title/tt0070328)
[The Man with the Golden Gun (1974)](http://www.imdb.com/title/tt0071807)
[The Spy who Loved Me (1977)](http://www.imdb.com/title/tt0076752)
[Moonraker (1979)](http://www.imdb.com/title/tt0079574)
[For Your Eyes Only (1981)](http://www.imdb.com/title/tt0082398)
[Octopussy (1983)](http://www.imdb.com/title/tt0086034)
[A View to a Kill (1985)](http://www.imdb.com/title/tt0090264)
[The Living Daylights (1987)](http://www.imdb.com/title/tt0093428)
[License to Kill (1989)](http://www.imdb.com/title/tt0097742)
[GoldenEye (1995)](http://www.imdb.com/title/tt0113189)
[Tomorrow Never Dies (1997)](http://www.imdb.com/title/tt0120347)
[The World is not Enough (1999)](http://www.imdb.com/title/tt0143145)
[Die Another Day (2002)](http://www.imdb.com/title/tt0246460)
[Casino Royale (2006)](http://www.imdb.com/title/tt0381061)
[Quantum of Solace (2008)](http://www.imdb.com/title/tt0830515)
[Skyfall (2012)](http://www.imdb.com/title/tt1074638)

**Comment by buhman** [comment]
Jesus fuck.

**Comment by buhman** [comment]
No 1080p:

* You Only Live Twice
* Diamonds are Forever
* Live and Let Die
* The Man with the Golden Gun
* A view to kill
* The living daylights
* license to kill

No source:

* The spy who loved me

Did not check the last 4, everything else is queued.
