### ISSUE TITLE
Fast and Furious Series

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#35]
- [The Fast and the Furious (2001)](http://www.imdb.com/title/tt0232500/)
- [2 Fast 2 Furious (2003)](http://www.imdb.com/title/tt0322259/)
- [The Fast and the Furious: Tokyo Drift (2006)](http://www.imdb.com/title/tt0463985/)
- [Fast and Furious (2009)](http://www.imdb.com/title/tt1013752/)
- [Fast Five (2011)](http://www.imdb.com/title/tt1596343/)
- [Fast and Furious 6 (2013)](http://www.imdb.com/title/tt1905041/)
- [Furious 7 (2015)](http://www.imdb.com/title/tt2820852/)

**Comment by buhman** [comment]
done.
