### ISSUE TITLE
Martial Arts Movies

### ISSUE THREAD

**Issue by HalosGhost** [buhman/erebor#37]
General
-------

[Drunken Master (1978)](http://www.imdb.com/title/tt0080179)
[Crouching Tiger, Hidden Dragon (2000)](http://www.imdb.com/title/tt0190332)
[Iron Monkey (1993)](http://www.imdb.com/title/tt0108148)
[House of Flying Daggers (2004)](http://www.imdb.com/title/tt0385004)

Ip Man
------

[Ip Man (2008)](http://www.imdb.com/title/tt1220719)
[Ip Man 2 (2010)](http://www.imdb.com/title/tt1386932)
[Ip Man: The Final Fight (2013)](http://www.imdb.com/title/tt2495118)
[The Legend is Born: Ip Man (2010)](http://www.imdb.com/title/tt1641638)

All are preferred to have both English dubs, original audio and english subtitles. Options galore!

**Comment by buhman** [comment]
all queued
